version: '3'

services:
  guacamole:
    environment:
      EXTENSIONS: auth-ldap,auth-duo
    image: oznu/guacamole
    ports:
    - 9600:8080
    volumes:
    - /guacamole/data/config:/config
    - /guacamole/data/record:/record
    restart: always
