version: '3'

services:
  guacamole:
    environment:
      EXTENSIONS: auth-ldap,auth-duo
    image: oznu/guacamole
    ports:
    - 8080:8080
    volumes:
    - /data/guacamole/config:/config
    - /data/guacamole/record:/record
    restart: always
